FROM eclipse-temurin:25-jdk-alpine AS build

WORKDIR /workspace
COPY pom.xml ./
COPY .mvn .mvn
COPY mvnw ./
RUN chmod +x mvnw
RUN ./mvnw dependency:go-offline -B

COPY src ./src
RUN ./mvnw clean package -DskipTests -B

FROM eclipse-temurin:25-jre-alpine

RUN apk add --no-cache \
    curl \
    && rm -rf /var/cache/apk/*

RUN addgroup -S appuser && adduser -S appuser -G appuser
WORKDIR /app
COPY --from=build /workspace/target/*.jar app.jar

RUN mkdir -p logs && chown -R appuser:appuser /app
USER appuser

EXPOSE 8080
ENTRYPOINT ["sh", "-c", "java $JAVA_OPTS $JVM_OPTS -jar app.jar"]
