ALTER TABLE clients
    ALTER COLUMN phone TYPE VARCHAR(30);

COMMENT ON COLUMN clients.phone IS
    'Client phone. Real Turkmenistan numbers fit in <= 13 chars (+99363xxxxxxx). Integration virtual phones generated by Client.generateIntegrationPhone follow the pattern "+993INT<serviceHash6>_<userHash<=8>" and can reach 22 chars; column was widened from 20 to 30 to accommodate them with headroom.';
